[package]
name = "send_usd"
version = "0.1.0"
edition = "2023_11"

[dependencies]
starknet = ">=2.5.4"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.10.0" }

# TODO: replace with tag after release
pyth = { git = "https://github.com/pyth-network/pyth-crosschain.git", tag = "pyth-starknet-contract-v0.1.0" }

[[target.starknet-contract]]
