import AppProvider from "@/providers/app-provider"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <AppProvider>
        <body className={inter.className}>
          <div className="container mx-auto flex h-screen w-[300px] flex-col items-center justify-center space-y-4">
            {children}
          </div>
        </body>
      </AppProvider>
    </html>
  )
}
