import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { Pool } from "pg";
import type { SolarSnapshotRecord } from "@packages/shared-types";
import type { SolarSnapshotRepository } from "./types.js";
const currentDir = dirname(fileURLToPath(import.meta.url)); const schemaPath = join(currentDir,"..","sql","schema.sql");
interface SnapshotRow { snapshot_id: string; site_id: string; batch: SolarSnapshotRecord["batch"]; quote: SolarSnapshotRecord["quote"]; climate: SolarSnapshotRecord["climate"]; reference_price: SolarSnapshotRecord["referencePrice"]; created_at: string | Date; }
function mapRowToSnapshot(row: SnapshotRow): SolarSnapshotRecord { return { snapshotId: row.snapshot_id, siteId: row.site_id, batch: row.batch, quote: row.quote, climate: row.climate, referencePrice: row.reference_price, createdAt: new Date(row.created_at).toISOString() }; }
export class PostgresSolarSnapshotRepository implements SolarSnapshotRepository { readonly mode = "postgres" as const; readonly #pool: Pool; constructor(databaseUrl: string) { this.#pool = new Pool({ connectionString: databaseUrl }); } async ensureReady(): Promise<void> { const schema = await readFile(schemaPath,"utf8"); await this.#pool.query(schema); } async create(snapshot: SolarSnapshotRecord): Promise<SolarSnapshotRecord> { await this.#pool.query(`INSERT INTO solarchain_snapshots (snapshot_id,site_id,batch,quote,climate,reference_price,created_at) VALUES ($1,$2,$3::jsonb,$4::jsonb,$5::jsonb,$6::jsonb,$7)`, [snapshot.snapshotId,snapshot.siteId,JSON.stringify(snapshot.batch),JSON.stringify(snapshot.quote),JSON.stringify(snapshot.climate),JSON.stringify(snapshot.referencePrice),snapshot.createdAt]); return snapshot; } async list(limit: number): Promise<SolarSnapshotRecord[]> { const result = await this.#pool.query<SnapshotRow>(`SELECT snapshot_id, site_id, batch, quote, climate, reference_price, created_at FROM solarchain_snapshots ORDER BY created_at DESC LIMIT $1`, [limit]); return result.rows.map(mapRowToSnapshot); } async getById(snapshotId: string): Promise<SolarSnapshotRecord | null> { const result = await this.#pool.query<SnapshotRow>(`SELECT snapshot_id, site_id, batch, quote, climate, reference_price, created_at FROM solarchain_snapshots WHERE snapshot_id = $1 LIMIT 1`, [snapshotId]); const row = result.rows[0]; return row ? mapRowToSnapshot(row) : null; } }
