import { DemoState } from "./types";

const DEMO_NOW_MS = Date.parse("2026-03-22T19:00:00.000Z");

export const demoState: DemoState = {
  nowMs: DEMO_NOW_MS,
  vault: {
    id: "guards-vault-001",
    name: "Main Treasury",
    chain: "cardano",
    stage: "normal",
    ladderStep: "auto_reentry",
    signers: ["addr1q...governance"],
    keepers: ["addr1q...keeper"],
  },
  positions: [
    {
      assetId: "ada",
      symbol: "ADA",
      role: "risk",
      amount: 125000,
      fiatValue: 56250,
      weight: 0.6,
    },
    {
      assetId: "usdm",
      symbol: "USDM",
      role: "stable",
      amount: 37500,
      fiatValue: 37500,
      weight: 0.4,
    },
  ],
  oracle: {
    feedId: "pyth-ada-usd",
    symbol: "ADA/USD",
    price: 0.25200284,
    emaPrice: 0.25131742,
    confidence: 0.00005284,
    publisherCount: 14,
    updatedAtMs: DEMO_NOW_MS - 2_000,
  },
  policy: {
    policyId: "guards-policy-001",
    primaryAssetId: "ada",
    primaryFeedId: "pyth-ada-usd",
    stableAssetId: "usdm",
    approvedRouteIds: ["dexhunter-ada-usdm"],
    portfolioFloorFiat: 80000,
    emergencyPortfolioFloorFiat: 70000,
    haircutBps: 150,
    maxStaleUs: 30_000_000,
    maxConfidenceBps: 200,
    cooldownUs: 600_000_000,
    watchDrawdownBps: 300,
    partialDrawdownBps: 700,
    fullExitDrawdownBps: 1200,
    reentryDrawdownBps: -500,
    partialStableTargetRatio: 0.5,
    reentryRiskTargetRatio: 0.6,
  },
  events: [
    {
      id: "evt-001",
      kind: "derisk_swap",
      stage: "partial_derisk",
      sourceSymbol: "ADA",
      destinationSymbol: "USDM",
      amount: 15000,
      route: "dexhunter-ada-usdm",
      timestamp: DEMO_NOW_MS - 3_600_000,
      status: "executed",
    },
    {
      id: "evt-002",
      kind: "derisk_swap",
      stage: "full_exit",
      sourceSymbol: "ADA",
      destinationSymbol: "USDM",
      amount: 45000,
      route: "dexhunter-ada-usdm",
      timestamp: DEMO_NOW_MS - 1_800_000,
      status: "executed",
    },
    {
      id: "evt-003",
      kind: "reentry_swap",
      stage: "normal",
      sourceSymbol: "USDM",
      destinationSymbol: "ADA",
      amount: 20000,
      route: "dexhunter-ada-usdm",
      timestamp: DEMO_NOW_MS - 600_000,
      status: "pending",
    },
  ],
  metrics: {
    liquidValue: 93750,
    stableRatio: 0.4,
    drawdownBps: 425,
    oracleFreshness: "2s ago",
  },
  frames: [
    {
      index: 0,
      balance: 100000,
      stableRatio: 0.2,
      stage: "normal",
      trigger: "Initial state",
      explanation: "Treasury operating within normal parameters.",
    },
    {
      index: 1,
      balance: 96000,
      stableRatio: 0.2,
      stage: "watch",
      trigger: "Drawdown > 300bps",
      explanation:
        "ADA price dropped 3%. Engine enters watch mode, monitoring closely.",
    },
    {
      index: 2,
      balance: 91000,
      stableRatio: 0.45,
      stage: "partial_derisk",
      trigger: "Drawdown > 700bps",
      explanation:
        "7% drawdown triggered partial de-risk. Swapped 25% of ADA to USDM.",
    },
    {
      index: 3,
      balance: 85000,
      stableRatio: 0.85,
      stage: "full_exit",
      trigger: "Drawdown > 1200bps / Floor breached",
      explanation:
        "Portfolio floor breached. Full stable exit executed to protect fiat value.",
    },
    {
      index: 4,
      balance: 93750,
      stableRatio: 0.4,
      stage: "normal",
      trigger: "Recovery > 500bps",
      explanation:
        "Price recovered past re-entry threshold. Auto re-entry restored risk allocation.",
    },
  ],
};
