/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.89.0
  Forc version: 0.60.0
  Fuel-Core version: 0.26.0
*/

import { Interface, Contract, ContractFactory } from "fuels";
import type { Provider, Account, AbstractAddress, BytesLike, DeployContractOptions, StorageSlot } from "fuels";
import type { TestContractAbi, TestContractAbiInterface } from "../TestContractAbi";

const _abi = {
  "encoding": "1",
  "types": [
    {
      "typeId": 0,
      "type": "()",
      "components": [],
      "typeParameters": null
    },
    {
      "typeId": 1,
      "type": "generic T",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 2,
      "type": "raw untyped ptr",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 3,
      "type": "struct Bytes",
      "components": [
        {
          "name": "buf",
          "type": 5,
          "typeArguments": null
        },
        {
          "name": "len",
          "type": 9,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 4,
      "type": "struct Price",
      "components": [
        {
          "name": "confidence",
          "type": 9,
          "typeArguments": null
        },
        {
          "name": "exponent",
          "type": 8,
          "typeArguments": null
        },
        {
          "name": "price",
          "type": 9,
          "typeArguments": null
        },
        {
          "name": "publish_time",
          "type": 9,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 5,
      "type": "struct RawBytes",
      "components": [
        {
          "name": "ptr",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "cap",
          "type": 9,
          "typeArguments": null
        }
      ],
      "typeParameters": null
    },
    {
      "typeId": 6,
      "type": "struct RawVec",
      "components": [
        {
          "name": "ptr",
          "type": 2,
          "typeArguments": null
        },
        {
          "name": "cap",
          "type": 9,
          "typeArguments": null
        }
      ],
      "typeParameters": [
        1
      ]
    },
    {
      "typeId": 7,
      "type": "struct Vec",
      "components": [
        {
          "name": "buf",
          "type": 6,
          "typeArguments": [
            {
              "name": "",
              "type": 1,
              "typeArguments": null
            }
          ]
        },
        {
          "name": "len",
          "type": 9,
          "typeArguments": null
        }
      ],
      "typeParameters": [
        1
      ]
    },
    {
      "typeId": 8,
      "type": "u32",
      "components": null,
      "typeParameters": null
    },
    {
      "typeId": 9,
      "type": "u64",
      "components": null,
      "typeParameters": null
    }
  ],
  "functions": [
    {
      "inputs": [],
      "name": "get_price",
      "output": {
        "name": "",
        "type": 4,
        "typeArguments": null
      },
      "attributes": null
    },
    {
      "inputs": [
        {
          "name": "update_data",
          "type": 7,
          "typeArguments": [
            {
              "name": "",
              "type": 3,
              "typeArguments": null
            }
          ]
        }
      ],
      "name": "update_price_feeds",
      "output": {
        "name": "",
        "type": 0,
        "typeArguments": null
      },
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": []
};

const _storageSlots: StorageSlot[] = [];

export const TestContractAbi__factory = {
  abi: _abi,

  storageSlots: _storageSlots,

  createInterface(): TestContractAbiInterface {
    return new Interface(_abi) as unknown as TestContractAbiInterface
  },

  connect(
    id: string | AbstractAddress,
    accountOrProvider: Account | Provider
  ): TestContractAbi {
    return new Contract(id, _abi, accountOrProvider) as unknown as TestContractAbi
  },

  async deployContract(
    bytecode: BytesLike,
    wallet: Account,
    options: DeployContractOptions = {}
  ): Promise<TestContractAbi> {
    const factory = new ContractFactory(bytecode, _abi, wallet);

    const contract = await factory.deployContract({
      storageSlots: _storageSlots,
      ...options,
    });

    return contract as unknown as TestContractAbi;
  }
}
