/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface FriendsGroupBetsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createMarket"
      | "hasWithdrawn"
      | "isParticipant"
      | "isTarget"
      | "markets"
      | "nextMarketId"
      | "placeBet"
      | "stakes"
      | "systemCancel"
      | "systemResolve"
      | "voteCancel"
      | "voteOutcome"
      | "voteResolve"
      | "voteToCancel"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BetPlaced"
      | "MarketCancelled"
      | "MarketCreated"
      | "MarketResolved"
      | "VoteCancel"
      | "VoteOutcome"
      | "Withdrawal"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createMarket",
    values: [
      BytesLike,
      BigNumberish,
      AddressLike,
      BigNumberish,
      AddressLike[],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "hasWithdrawn",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isParticipant",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isTarget",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextMarketId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakes",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "systemCancel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "systemResolve",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voteCancel",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voteOutcome",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voteResolve",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "voteToCancel",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createMarket",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasWithdrawn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isParticipant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isTarget", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "markets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextMarketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "systemCancel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "systemResolve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voteCancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voteOutcome",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteResolve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "voteToCancel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace BetPlacedEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    outcome: BigNumberish,
    amt: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    user: string,
    outcome: bigint,
    amt: bigint
  ];
  export interface OutputObject {
    id: bigint;
    user: string;
    outcome: bigint;
    amt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCancelledEvent {
  export type InputTuple = [id: BigNumberish, forced: boolean];
  export type OutputTuple = [id: bigint, forced: boolean];
  export interface OutputObject {
    id: bigint;
    forced: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketCreatedEvent {
  export type InputTuple = [id: BigNumberish, metadataHash: BytesLike];
  export type OutputTuple = [id: bigint, metadataHash: string];
  export interface OutputObject {
    id: bigint;
    metadataHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MarketResolvedEvent {
  export type InputTuple = [
    id: BigNumberish,
    outcome: BigNumberish,
    forced: boolean
  ];
  export type OutputTuple = [id: bigint, outcome: bigint, forced: boolean];
  export interface OutputObject {
    id: bigint;
    outcome: bigint;
    forced: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCancelEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    cancelVote: boolean
  ];
  export type OutputTuple = [id: bigint, user: string, cancelVote: boolean];
  export interface OutputObject {
    id: bigint;
    user: string;
    cancelVote: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteOutcomeEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    outcome: BigNumberish
  ];
  export type OutputTuple = [id: bigint, user: string, outcome: bigint];
  export interface OutputObject {
    id: bigint;
    user: string;
    outcome: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawalEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [id: bigint, user: string, amount: bigint];
  export interface OutputObject {
    id: bigint;
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface FriendsGroupBets extends BaseContract {
  connect(runner?: ContractRunner | null): FriendsGroupBets;
  waitForDeployment(): Promise<this>;

  interface: FriendsGroupBetsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createMarket: TypedContractMethod<
    [
      metadataHash: BytesLike,
      deadline: BigNumberish,
      resolverAddr: AddressLike,
      shareSize: BigNumberish,
      targetList: AddressLike[],
      outcomesCount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  hasWithdrawn: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isParticipant: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  isTarget: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  markets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint
      ] & {
        id: bigint;
        creator: string;
        resolver: string;
        metadataHash: string;
        deadline: bigint;
        shareSize: bigint;
        resolved: boolean;
        cancelled: boolean;
        winningOutcome: bigint;
      }
    ],
    "view"
  >;

  nextMarketId: TypedContractMethod<[], [bigint], "view">;

  placeBet: TypedContractMethod<
    [id: BigNumberish, outcome: BigNumberish],
    [void],
    "payable"
  >;

  stakes: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike, arg2: BigNumberish],
    [bigint],
    "view"
  >;

  systemCancel: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  systemResolve: TypedContractMethod<
    [id: BigNumberish, outcome: BigNumberish, metadataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  voteCancel: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  voteOutcome: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  voteResolve: TypedContractMethod<
    [id: BigNumberish, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;

  voteToCancel: TypedContractMethod<
    [id: BigNumberish, v: boolean],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createMarket"
  ): TypedContractMethod<
    [
      metadataHash: BytesLike,
      deadline: BigNumberish,
      resolverAddr: AddressLike,
      shareSize: BigNumberish,
      targetList: AddressLike[],
      outcomesCount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasWithdrawn"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isParticipant"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isTarget"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "markets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint
      ] & {
        id: bigint;
        creator: string;
        resolver: string;
        metadataHash: string;
        deadline: bigint;
        shareSize: bigint;
        resolved: boolean;
        cancelled: boolean;
        winningOutcome: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextMarketId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<
    [id: BigNumberish, outcome: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "stakes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike, arg2: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "systemCancel"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "systemResolve"
  ): TypedContractMethod<
    [id: BigNumberish, outcome: BigNumberish, metadataHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voteCancel"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "voteOutcome"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "voteResolve"
  ): TypedContractMethod<
    [id: BigNumberish, outcome: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voteToCancel"
  ): TypedContractMethod<[id: BigNumberish, v: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "BetPlaced"
  ): TypedContractEvent<
    BetPlacedEvent.InputTuple,
    BetPlacedEvent.OutputTuple,
    BetPlacedEvent.OutputObject
  >;
  getEvent(
    key: "MarketCancelled"
  ): TypedContractEvent<
    MarketCancelledEvent.InputTuple,
    MarketCancelledEvent.OutputTuple,
    MarketCancelledEvent.OutputObject
  >;
  getEvent(
    key: "MarketCreated"
  ): TypedContractEvent<
    MarketCreatedEvent.InputTuple,
    MarketCreatedEvent.OutputTuple,
    MarketCreatedEvent.OutputObject
  >;
  getEvent(
    key: "MarketResolved"
  ): TypedContractEvent<
    MarketResolvedEvent.InputTuple,
    MarketResolvedEvent.OutputTuple,
    MarketResolvedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCancel"
  ): TypedContractEvent<
    VoteCancelEvent.InputTuple,
    VoteCancelEvent.OutputTuple,
    VoteCancelEvent.OutputObject
  >;
  getEvent(
    key: "VoteOutcome"
  ): TypedContractEvent<
    VoteOutcomeEvent.InputTuple,
    VoteOutcomeEvent.OutputTuple,
    VoteOutcomeEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawal"
  ): TypedContractEvent<
    WithdrawalEvent.InputTuple,
    WithdrawalEvent.OutputTuple,
    WithdrawalEvent.OutputObject
  >;

  filters: {
    "BetPlaced(uint256,address,uint256,uint256)": TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
    BetPlaced: TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;

    "MarketCancelled(uint256,bool)": TypedContractEvent<
      MarketCancelledEvent.InputTuple,
      MarketCancelledEvent.OutputTuple,
      MarketCancelledEvent.OutputObject
    >;
    MarketCancelled: TypedContractEvent<
      MarketCancelledEvent.InputTuple,
      MarketCancelledEvent.OutputTuple,
      MarketCancelledEvent.OutputObject
    >;

    "MarketCreated(uint256,bytes32)": TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;
    MarketCreated: TypedContractEvent<
      MarketCreatedEvent.InputTuple,
      MarketCreatedEvent.OutputTuple,
      MarketCreatedEvent.OutputObject
    >;

    "MarketResolved(uint256,uint8,bool)": TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;
    MarketResolved: TypedContractEvent<
      MarketResolvedEvent.InputTuple,
      MarketResolvedEvent.OutputTuple,
      MarketResolvedEvent.OutputObject
    >;

    "VoteCancel(uint256,address,bool)": TypedContractEvent<
      VoteCancelEvent.InputTuple,
      VoteCancelEvent.OutputTuple,
      VoteCancelEvent.OutputObject
    >;
    VoteCancel: TypedContractEvent<
      VoteCancelEvent.InputTuple,
      VoteCancelEvent.OutputTuple,
      VoteCancelEvent.OutputObject
    >;

    "VoteOutcome(uint256,address,uint8)": TypedContractEvent<
      VoteOutcomeEvent.InputTuple,
      VoteOutcomeEvent.OutputTuple,
      VoteOutcomeEvent.OutputObject
    >;
    VoteOutcome: TypedContractEvent<
      VoteOutcomeEvent.InputTuple,
      VoteOutcomeEvent.OutputTuple,
      VoteOutcomeEvent.OutputObject
    >;

    "Withdrawal(uint256,address,uint256)": TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
    Withdrawal: TypedContractEvent<
      WithdrawalEvent.InputTuple,
      WithdrawalEvent.OutputTuple,
      WithdrawalEvent.OutputObject
    >;
  };
}
