/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FriendsGroupBets } from "./FriendsGroupBets";
export * as factories from "./factories";
export { FriendsGroupBets__factory } from "./factories/FriendsGroupBets__factory";
