[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_anchor = "FpmpVrP57C6ADT8d4dQp9TkM1vmxohZJ5WEQQc9RGLPY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
