export const OPCODES = {
    CONFIGURE: 0x2,
    ONCHAIN_GETTER_OPERATION: 0x7,
    ONCHAIN_GETTER_PROCESS: 0x8,
    PROXY_OPERATION: 0x4,
    JETTON_TRANSFER: 0xf8a7ea5,
}

export const PYTH_OPCODES = {
    UPDATE_PRICE_FEEDS: 0x5,
    RESPONSE_ERROR: 0x10002,
}

export const JETTON_OPCODES = {
    TRANSFER: 0x0f8a7ea5,
    TRANSFER_NOTIFICATION: 0x7362d09c,
    EXCESSES: 0xd53276db,
}
